export const FETCH_JOB_PENDING = 'FETCH_JOB_PENDING';
export const FETCH_JOB_FULFILLED = 'FETCH_JOB_FULFILLED';
export const FETCH_JOB_REJECTED = 'FETCH_JOB_REJECTED';
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED';
export const FETCH_COMPANIES_PENDING = 'FETCH_COMPANIES_PENDING';
export const FETCH_COMPANIES_FULFILLED = 'FETCH_COMPANIES_FULFILLED';
export const FETCH_COMPANIES_REJECTED = 'FETCH_COMPANIES_REJECTED';
//user
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';

export const ADD_USER_PENDING = 'ADD_USER_PENDING';
export const ADD_USER_FULFILLED = 'ADD_USER_FULFILLED';
export const ADD_USER_REJECTED = 'ADD_USER_REJECTED';